opt_in_rules:
  - array_init
  - explicit_init
  - fatal_error_message
  - first_where
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_interface_builder
  - redundant_nil_coalescing
  - sorted_imports
  - vertical_whitespace_closing_braces
  - weak_delegate

disabled_rules:
  - explicit_self
  - trailing_whitespace
  - vertical_whitespace
  - line_length
  - trailing_comma
  - implicitly_unwrapped_optional
  - for_where
  - trailing_closure
  - nesting
  - statement_level
  - colon
  - comma
  - control_statement
  - empty_count
  - large_tuple
  - type_body_length
  - function_body_length
  - identifier_name
  - cyclomatic_complexity

excluded:
  - Pods
  - Sources/ExcludedFolder
  - Sources/ExcludedFile.swift
  - .build
  - DerivedData

included:
  - Sources

allow_zero_lintable_files: false
strict: false
