opt_in_rules:
  - array_init
  - closure_spacing
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_interface_builder
  - redundant_nil_coalescing
  - sorted_imports
  - strict_fileprivate
  - strong_iboutlet
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - weak_delegate

disabled_rules:
  - explicit_self
  - trailing_whitespace
  - vertical_whitespace

line_length:
  warning: 120
  error: 250

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
  statement_level:
    warning: 5

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
  excluded:
    - id
    - x
    - y
    - z
    - URL

large_tuple:
  warning: 3
  error: 4
